### ISSUE TITLE
Fullscreen view has 2 header popups

### ISSUE THREAD

**Issue by hadess** [Ippytraxx/gnome-twitch#12]

**Comment by Ippytraxx** [comment]
Can you post a screenshot or something? There shouldn't be two popups. There is one header bar in the application and one header bar in the popup, however the one in the application shouldn't be visible in fullscreen mode.

**Comment by hadess** [comment]
![twitch-2-headerbars](https://cloud.githubusercontent.com/assets/769861/10369400/52c6cef2-6dda-11e5-950f-8c3029dda3cb.png)

**Comment by Ippytraxx** [comment]
What window manager are you running?

**Comment by hadess** [comment]
gnome-shell

**Comment by Ippytraxx** [comment]
Well beats me... The first header bar should be hidden because it's part of the window decoration. If the window says it's in fullscreen but it's really not, then not much I can do without really digging into which I don't have time to right now. Plus even if I could tell, I can't dynamically hide the window decoration like I can the popup, so it would always be visible.

I'm also running gnome-shell and I don't have any problems.

**Comment by hadess** [comment]
Bug in gnome-twitch. See the window-state-event documentation. You're essentially stopping GTK+ from hiding the titlebar and it works by luck on your system:
```
diff --git a/src/gt-win.c b/src/gt-win.c
index 0ed75f7..6b0d4ff 100644
--- a/src/gt-win.c
+++ b/src/gt-win.c
@@ -116,7 +116,7 @@ static GActionEntry win_actions[] =
     {"show_settings", show_settings_cb, NULL, NULL, NULL}
 };
 
-static void
+static gboolean
 window_state_cb(GtkWidget* widget,
                 GdkEventWindowState* evt,
                 gpointer udata)
@@ -133,6 +133,7 @@ window_state_cb(GtkWidget* widget,
         g_object_notify_by_pspec(G_OBJECT(self), props[PROP_FULLSCREEN]);
     }
 
+    return FALSE;
 }
 
 static void
```

**Comment by Ippytraxx** [comment]
Yep my bad, didn't completely read the docs.
