### ISSUE TITLE
Suggestion: Lower build dependencies

### ISSUE THREAD

**Issue by h1z1** [Ippytraxx/gnome-twitch#126]
CentOS 6/7.   I don't know if they are hard requirements or you really are building against bleeding edge libraries but after 2 hours of dependency hell, I've given up.  The biggest problems are Webkit4 and clutter-gst3, they are entire major releases above even EPEL.

**Comment by jangernert** [comment]
Not the developer of gnome-twitch, just my 2ct developing my own gtk+ application:
Webkitgtk-4 and Webkitgtk-3 support at the same time should not be tooooo hard, since the API basically is the same (maybe a few added API calls). Originally the API break was introduced to make the old version that still includes webkit1 and the new version that removed webkit1 installable side by side. But these things seem small at first and then add up over time and make the maintenance more difficult.

**Comment by Ippytraxx** [comment]
Hmm, I can probably do what @jangernert suggested and add support for WebKitGTK-3, however clutter-gst3 would be hard to replace or make modular with older versions.

What version of MPV does CentOS currently include because I am currently working on a MPV backend that will hopefully solve these situations where the GStreamer stack doesn't work.

**Comment by h1z1** [comment]
Not sure what MPV is in reference to but the current version of clutter  is  tagged clutter-gst2-2.0.12, appears to be clutter 1.2 upstream?   Though it could be argued Fedora 22 or better is required (something entirely insane), or possibly CentOS 6 but this is even for Centos 7.  

Is it possible to ship or fall back to a local copy in the build dir?

**Comment by Ippytraxx** [comment]
MPV is a popular MPlayer replacement that is available on most distros. Unfortunately the API's are too different between clutter-gst-2 and clutter-gst-3 plus I think it's quite reasonable to expect that any distro that ships GTK+ >= 3.16 should also ship clutter-gst-3. 

Packaging a local version of clutter-gst-3 is possible but I don't really have the time to do it, especially because I don't want to deal with autotools.

**Comment by h1z1** [comment]
Ah.. another Ubuntu /Debianism.   It may be popular but it isn't standard.  I don't think it even comes with their own LTS releases?   Never heard of Meson nor WrapDB either before now.   

Either way I certainly don't mean you any disrespect.  Thanks for your time.

**Comment by Ippytraxx** [comment]
Alright, sorry this didn't work out.
