### ISSUE TITLE
Graphical artifacts at the bottom of the video

### ISSUE THREAD

**Issue by cra0zy** [Ippytraxx/gnome-twitch#37]
https://youtu.be/uMlEk7SGcKo

System info:
Ubuntu 15.10
Open source AMD Driver

**Comment by Ippytraxx** [comment]
Same problem as #19, seems to be a problem with the open source AMD drivers. Unfortunately the GetDeb version is pretty old and using the old player. I've [asked](https://github.com/ckorn/GetDeb/issues/10) the GetDeb maintainers to update it to the latest tagged release (v0.1.0) for 15.10, but they don't seem to have done it yet.

In the meantime you can download the 0.1.0 release and follow in the install instructions in the readme (probably use the autotools release because I don't think Meson is up-to-date on 15.10 either).

I will try to get a PPA going when I have time so I can keep that one in sync with releases.

**Comment by Ippytraxx** [comment]
I've now added a PPA. Could you please test it?

**Comment by cra0zy** [comment]
Works perfectly, nice work.
