### ISSUE TITLE
Hide menubar on fullscreen (or remove it altogether)

### ISSUE THREAD

**Issue by 1player** [Ippytraxx/gnome-twitch#45]
When the player is fullscreen, the menu is still visible, while providing no purpose: the only available action is to change the video quality, and that is also available on the "action bar" that pops up when moving the mouse.

Perhaps consider removing the menu bar altogether.

**Comment by Ippytraxx** [comment]
Is this what you are getting https://github.com/Ippytraxx/gnome-twitch/issues/12?

What version are you running, because I thought I fixed this?

**Comment by Ippytraxx** [comment]
No reply.

**Comment by W4RH4WK** [comment]
Hi there, I am encountering the same issue, the menu bar containing the "Application" menu is not hidden in fullscreen. I am using the ppa version (0.1.0-5) on XUbuntu 15.10.

**Comment by Ippytraxx** [comment]
Are you getting two meubars showing or just one that doesn't disappear? Can you try moving the mouse around on the video at least 50 pixels below the top. I have a mouse listener that should hide the bar whenever the mouse is moved 50 pixels below the top.

**Comment by W4RH4WK** [comment]
The gtk3 HeaderBar hides perfectly fine if the mouse is moved down from the top. But the smaller menu bar does not disappear at all.

HeaderBar shown:
![mouse_inside_menubar](https://cloud.githubusercontent.com/assets/328798/12117791/49bb8bf2-b3c3-11e5-9387-b35eea540142.png)

HeaderBar hidden:
![mouse_outside_menubar](https://cloud.githubusercontent.com/assets/328798/12117800/51a6f932-b3c3-11e5-956f-5552f6018e81.png)

I could be a problem since I am on XFCE and some parts are still gtk2, but other gtk3 applications (gnome-calculator) work fine:
![image](https://cloud.githubusercontent.com/assets/328798/12117850/87e97830-b3c3-11e5-9b28-ffc28322fe88.png)

**Comment by Ippytraxx** [comment]
Wow that's wierd, according to the documentation this should be placed into the headerbar automatically just like in gnome-calculator, at least from what I've understood. I'll fix it next week when I get back.

**Comment by jhaye** [comment]
Can confirm that the menu bar is now gone on Xfce when compiling the current "develop" branch with 4c1bf49.
![Image](https://i.imgur.com/BdAoMQ1.png)

**Comment by W4RH4WK** [comment]
I tried compiling from the current development branch, but `meson` fails for me (likewise with the master branch)

```
> meson --prefix /usr -Ddo-post-install=true ..
The Meson build system
Version: 0.21.0
Source dir: /home/w4rh4wk/.local/src/gnome-twitch
Build dir: /home/w4rh4wk/.local/src/gnome-twitch/build
Build type: native build

Meson encountered an error in file meson.build, line 4, column 32:
lexer
```

**Comment by Ippytraxx** [comment]
@jhaye Thanks for the confirmation.
@W4RH4WK You need meson 0.26.0 or greater.

**Comment by jhaye** [comment]
Can we please get this cherrypicked into master?

**Comment by Ippytraxx** [comment]
@jhaye Sure! Should've done this on master in the first place, my bad.

**Comment by jhaye** [comment]
Thank you.
