### ISSUE TITLE
[IDEA] Add Twitch account and new streams notiffications support to the app

### ISSUE THREAD

**Issue by sergioad** [Ippytraxx/gnome-twitch#61]
Hello friends I have some ideas for the app

1.- add Twitch account support for speaking in the chat
2.- with the twitch support you could add an option to see a list of your followed channels, you can click on one of them to see the channe's profie with a list of the last streams
3.- add notiffications of new live streams with a button to go directly to it

I do not know if this app allready has these features because I tried a .deb of it and I do not know if it was outdated but anyway there are my suggestions :smile: 

EDIT: I saw that it actually has the Twitch account support but when you are loged in the menu entry does not changes, it could change to a see profile  option where you can see your Twitch profile

**Comment by jangernert** [comment]
I never got what the difference between a "favorite" channel without twitch account and the "followed" channels in the twitch account was^^
I think once you log in the favorites should be replaced by your followed channel :)

**Comment by sergioad** [comment]
favorite ones are those wich you love, the followed ones are those wich you are interested on

**Comment by jangernert** [comment]
If you don't like a channel why would you follow it? To me that's the same thing. Only difference is "favorites" are managed by gnome-twitch locally and "followed" are tied to the twitch account.

**Comment by Ippytraxx** [comment]
Sorry guys for any confusion, I'll be creating some proper documentation soon. 

@jangernert is right though, "favourites" are when you are not logged in "follows" are the exact same thing except when you are. I have done it this way because I want people to be able to get as much functionality as possible even if you don't have an account.

@sergioad Thanks for the ideas and I again apologise for the lack of information. Currently on the master branch there is already the ability to log in a use Twitch chat. Notifications should also come up for any channel that is favourited when it comes online. Also I'll be adding more Twitch account features soon, currently I am just working on general functionality for everyone and then add account specific stuff.

Well my exams are finally over so I'll try to keep everyone updated. Thanks for the support!

**Comment by sergioad** [comment]
thank you to you @Ippytraxx, I hope see GNOME twitch with online favorited channels and I hope to see this project and the app grow up with the time and a good job :smile:

**Comment by sergioad** [comment]
@Ippytraxx how is going the development of the 2.0 release? do you think it could come with some of my suggested twitch integration?

**Comment by Ippytraxx** [comment]
@sergioad 1 and 3 will be in 0.2.0. Your second proposal will come in a later version shortly after, maybe 0.2.1 or something. I just got a tonne of unexpected shit to do at  uni that I didn't really anticipate so development has been a bit slow recently. But it will definitely pick up!

**Comment by sergioad** [comment]
@Ippytraxx I see :smile: and why do you not upload a git copr repo with git built GNOME twitch packages for Fedora with builds for Fc23 while the v2.0 is ready? could be a cool move

**Comment by Ippytraxx** [comment]
I've split this in up into #141 and #142 which both will be done for 0.3.0

**Comment by sergioad** [comment]
Thank you very much friend :smile:
