### ISSUE TITLE
Almost every key triggers play/pause

### ISSUE THREAD

**Issue by terzag** [Ippytraxx/gnome-twitch#88]
Using Gnome Twitch (from the PPA) on Ubuntu 15.10 with Mate. Might be a DE-related issue.

Pretty much every key pressed when the window has focus is intercepted by Gnome Twitch and toggles play/pause. It even does it with "dead" keys, i.e. if I'm watching a stream in fullscren and press alt + enter, it leaves fullscreen mode but first pauses playing because of the alt key.

I haven't tested all the keys, some don't trigger that behaviour: Esc (as stated above), Enter, Backspace, Function keys (F1-F12) don't do anything while letters/digits/punctuation, Ctrl, Alt, Del do.

It's a bit weird and pretty annoying.

**Comment by Ippytraxx** [comment]
Yeah it's a bug that I unfortunately forgot to fix before 0.1.0.

**Comment by terzag** [comment]
Ok, nice to know. Is it fixed in the current GIT version?

**Comment by Ippytraxx** [comment]
I've removed play/pause functionality in newer versions because I felt it was pretty useless. The "pause" button was actually a stop button and just reloaded the stream. If a user wants to stop a stream, they can just close it and open it again when they feel like.

So in short this problem no longer exists :)
